invoice_dir: C:/Users/theia/Documents/Data/Year 4 Sem 1/BT3101 BUSINESS ANALYTICS CAPSTONE/Invoices
clean_database: True

categories:
  Telco:
    - M1
    - CSL Mobile Limited
    - NTT
    - Singtel
    - StarHub Ltd

  Consultants:
    - BCG Pte Ltd
    - Mckinsey & Company

  Services:
    - Canon Singapore Pte Ltd
    - Oracle Corporation

  Hardware:
    - Dell Singapore Pte Ltd
    - NCS Pte Ltd

